In [1]:
import numpy as np
import pandas as pd
import statistics as st
from scipy.stats import kurtosis, skew
import matplotlib.pyplot as plt
import seaborn as sns
import math
import numpy as np
from scipy import stats
from scipy.stats import norm, t
import warnings
warnings.filterwarnings('ignore')

In [40]:
df = pd.read_csv("DS1_C8_Computers_Data_Project.csv") # read the file

### Task 1

The advertising budget spent on promoting premium computers in 2023 is increased as compared to 2022. The mean advertising budget was 221.3 billion dollars in 2022 and it was 222.2 billion dollars in 2023. A promoter in this company
believes that the average advertising budget is higher than that of 2022. Priya, a data analyst, randomly selected 40 premium computers to check this notion.
Use a 5% level of significance to test Maya's hypothesis. Consider normally distribution in the population and standard deviation is 74.83.

H0 : The advertising budget spent on promoting premium computers in 2023 is lesser or equal to 2022
H1 : The advertising budget spent on promoting premium computers in 2023 is greater than 2022

The population standard deviation is known and sample > 30 
So we need to perform z test
It is one sample test
The type is one tail right

In [13]:
population_mean = 221.3
population_stdev = 74.83

In [15]:
sample_mean = 222.2
n = 40

In [17]:
alpha=0.05

In [19]:
z_statistics = (sample_mean - population_mean) / (population_stdev / math.sqrt(n))

In [21]:
p_value = norm.sf(abs(z_statistics))

In [23]:
z_critical = norm.ppf(1 - alpha)

Decision rule

If p_value < alpha - Reject null hypothesis

In [25]:
print("The z_statistics is ", z_statistics)
print("The p_value is ", p_value)
print("The z_critical is ", z_critical)

The z_statistics is  0.07606708256451877
The p_value is  0.4696828642738865
The z_critical is  1.6448536269514722

INTERPRETATION

We can see p_value > alpha 
The value 0.46 > 0.05
We cannot reject null hypothesis we want to accept the null hypothesis

Business Implements

From the z test we cannot reject the null hypothesis
So, The advertising budget spent on promoting premium computers in 2023 is lesser or equal to 2022 not greater than 2022.

### Task-2

Is there a statistically significant difference in the average price of computers with CD players and computers without CD players? Use 5% of the significance level for the test.

In [42]:
computers_with_CD_players = df.loc[df["cd"] == "yes"]
computers_with_CD_players

,index,price,speed,hd,ram,screen,cd,multi,premium,ads_2022,ads_2023,trend
6,7,1720,25,170,4,14,yes,no,yes,94,104,1
30,31,1920,33,170,4,14,yes,no,yes,94,94,1
63,64,2220,33,250,4,14,yes,no,yes,94,94,1
70,71,4020,66,500,8,14,yes,no,yes,94,94,1
77,78,3220,66,340,8,15,yes,no,yes,94,94,1
...,...,...,...,...,...,...,...,...,...,...,...,...
6253,6254,2154,66,850,16,15,yes,no,yes,39,70,35
6255,6256,2223,66,850,16,15,yes,yes,yes,39,70,35
6256,6257,2654,100,1200,24,15,yes,no,yes,39,70,35
6257,6258,2195,100,850,16,15,yes,no,yes,39,70,35
6258,6259,2490,100,850,16,17,yes,no,yes,39,70,35

In [48]:
computers_with_no_CD_players = df.loc[df["cd"] == "no"]
computers_with_no_CD_players

,index,price,speed,hd,ram,screen,cd,multi,premium,ads_2022,ads_2023,trend
0,1,1499,25,80,4,14,no,no,yes,94,94,1
1,2,1795,33,85,2,14,no,no,yes,94,94,1
2,3,1595,25,170,4,15,no,no,yes,94,94,1
3,4,1849,25,170,8,14,no,no,no,94,94,1
4,5,3295,33,340,16,14,no,no,yes,94,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...
6240,6241,1595,100,528,8,14,no,no,yes,39,70,35
6246,6247,1554,66,528,8,14,no,no,yes,39,70,35
6247,6248,1654,100,528,8,14,no,no,yes,39,70,35
6252,6253,1690,66,1200,8,14,no,no,yes,39,70,35
6254,6255,1690,100,528,8,15,no,no,yes,39,70,35

H0 : There is no statistically significant difference in the average price of computers with CD players and computers without CD players
H1 : There a statistically significant difference in the average price of computers with CD players and computers without CD players

The population stdev is known
The sample size > 30 
so we need to perform z test
The type is two sample independant

In [44]:
mean1 = st.mean(computers_with_CD_players["price"])
stdev1 = st.stdev(computers_with_CD_players["price"])

In [50]:
mean2 = st.mean(computers_with_no_CD_players["price"])
stdev2 = st.stdev(computers_with_no_CD_players["price"])

In [52]:
shape1 = computers_with_CD_players.shape
shape2 = computers_with_no_CD_players.shape

In [54]:
n1 = shape1[0]
n2 = shape2[0]

In [56]:
print("The mean of the computer with cd player is ", mean1)
print("The stdev of the computer with cd player is ", stdev1)
print("The mean of the computer with no cd player is ", mean2)
print("The stdev of the computer with no cd player is ", stdev2)
print("The total sample of computer with cd player is ", n1)
print("The total sample of computer with no cd player is ", n2)

The mean of the computer with cd player is  2342.6055708390645
The stdev of the computer with cd player is  527.4477919505294
The mean of the computer with no cd player is  2112.8119964189796
The stdev of the computer with no cd player is  603.494237086272
The total sample of computer with cd player is  2908
The total sample of computer with no cd player is  3351

In [58]:
alpha = 0.05

In [60]:
z_statistics = (mean1 - mean2) / math.sqrt(((stdev1 ** 2) / n1) + ((stdev2 ** 2) / n2))

In [62]:
p_value = norm.sf(abs(z_statistics))*2

In [64]:
z_critical = norm.ppf(1 - alpha / 2)

In [78]:
print("The z_statistics is ", z_statistics)
print("The p_value is ", p_value)
print("The z_critical is ", z_critical)

The z_statistics is  16.07486310306849
The p_value is  3.8283817362952e-58
The z_critical is  1.959963984540054

Decision Rule 

If p_value < alpha - Reject null hypothesis

INTERPRETATION --

p_value < alpha
so we reject null hypothesis we are not accept the null hypothesis

Business Implements

From the z test we reject null hypothesis
There is a statistically significant difference in the average price of computers with CD players and computers without CD players.
The average price is not same.

### Task-3

a) Identify Price Discrepancy for Premium Computers
Determine if the mean price of premium computers differs significantly from $2200?
To examine this, select 25 samples of premium computers randomly from the data. Assume the data is normally distributed in the population. Use a 5% significance level to test this hypothesis.

In [ ]:
H0 : the mean price of premium computers is $2200
H1 : the mean price of premium computers differs significantly from $2200

In [83]:
population_mean = 2200

No standard deviation is given 
sample size < 30
So we need to perform t test 
One sample t test
Two tailed test

In [85]:
alpha = 0.05

In [87]:
premium_sample = df.loc[df["premium"] == "yes"]

In [89]:
premium_sample_data = premium_sample.sample(n = 25, random_state = 1, replace = True)

In [91]:
n = 25
dof = n - 1

In [93]:
sample_mean = st.mean(premium_sample_data["price"])
sample_stdev = st.stdev(premium_sample_data["price"])

In [95]:
t_statistics = (sample_mean - population_mean ) / (sample_stdev / math.sqrt(n))

In [97]:
p_value = t.sf(abs(t_statistics), dof)*2

In [99]:
t_critical = t.ppf(1-alpha / 2, dof)

In [101]:
print(f"The t_statistics is ", t_statistics)
print(f"The p_value is ", p_value)
print(f"The t_critical is ", t_critical)

The t_statistics is  -0.8768074614633947
The p_value is  0.3892836526199208
The t_critical is  2.0638985616280205

INTERPRETATION --
p_value > alpha 
(0.38 > 0.05) - We cannot reject null hypothesis
We accpet null hypothesis

Business Implements
From the t test we accept null hypothesis
So the mean price of premium computers is $2200
There is no significant difference between them

Task 3 (cont'd)

b) Analyze price disparity between premium and non-premium computers.
Is there a significant difference in the mean prices of premium and non-premium computers?
Assume that the prices are normally distributed and that the population variances are approximately equal. Use a 5% significance level to test this hypothesis.

H0 : there a no significant difference in the mean prices of premium and non-premium computers
H1 : there a significant difference in the mean prices of premium and non-premium computers?

Population Stdev is unknown 
We need to perform t test
It is two sample
two tailed

In [107]:
non_premium_sample = df.loc[df["premium"] == "no"]

In [109]:
mean1 = st.mean(premium_sample["price"])
mean2 = st.stdev(non_premium_sample["price"])
stdev1 = st.mean(premium_sample["price"])
stdev2 = st.stdev(non_premium_sample["price"])
n1 = premium_sample.shape[0]
n2 = non_premium_sample.shape[0]
dof = n1 + n2 - 2

In [111]:
alpha=0.05

In [113]:
t_statistics = mean1 - mean2 / math.sqrt((stdev1 ** 2)/n1 + (stdev2 ** 2)/n2)

In [115]:
p_value = t.sf(abs(t_statistics), dof)*2

In [117]:
t_critical = t.ppf(1 - alpha / 2, dof)

In [119]:
print(f"The is t_statistics", t_statistics)
print(f"The is p_value", p_value)
print(f"The is t_critical", t_critical)

The is t_statistics 2187.608711868042
The is p_value 0.0
The is t_critical 1.9603431954063062

INTERPRETATION 
p_value < alpha - Reject null hypothesis

Business Implements

From the t test we reject null hypothesis
So there a no significant difference in the mean prices of premium and non-premium computers
The mean of both the computers are same